/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SoadFreyleC.vistas;

import SoadFreyleC.bd.crud.UsuarioJpaController;
import SoadFreyleC.bd.crud.exceptions.PreexistingEntityException;
import SoadFreyleC.bd.tablas.Usuario;
import SoadFreyleC.bd.tablas.Usuario_;
import java.awt.Toolkit;
import java.util.Date;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.PersistenceException;
import javax.swing.JOptionPane;

/**
 *
 * @author ODETH
 */
public class VentanaCrud extends javax.swing.JDialog {

    /**
     * Creates new form VentanaCrud
     */
    public VentanaCrud(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CampoCedula = new javax.swing.JTextField();
        CampoPassword1 = new javax.swing.JPasswordField();
        CampoNombre = new javax.swing.JTextField();
        CampoEmail = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        radioMasculino = new javax.swing.JRadioButton();
        radioFemenino = new javax.swing.JRadioButton();
        radioOtros = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        opcCine = new javax.swing.JCheckBox();
        opcLeer = new javax.swing.JCheckBox();
        opcProgramar = new javax.swing.JCheckBox();
        opcDeportes = new javax.swing.JCheckBox();
        comboSeleccion = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CampoFecha = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        CampoPassword2 = new javax.swing.JPasswordField();
        botonCancelarCrud = new javax.swing.JButton();
        botonAgregarCrud = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORMULARIO");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true), "Datos del Usuario:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(0, 255, 51))); // NOI18N

        jLabel1.setText("Cedula:");

        jLabel2.setText("Password:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Email:");

        jLabel5.setText("Fecha:");

        CampoCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoCedulaKeyTyped(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true), "Genero:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(0, 255, 0))); // NOI18N

        radioMasculino.setText("Masculino");

        radioFemenino.setText("Femenino");

        radioOtros.setText("Otros");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(radioMasculino)
                .addGap(10, 10, 10)
                .addComponent(radioFemenino)
                .addGap(18, 18, 18)
                .addComponent(radioOtros)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioMasculino)
                    .addComponent(radioFemenino)
                    .addComponent(radioOtros))
                .addGap(12, 12, 12))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 2, true), "Pasatiempos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14), new java.awt.Color(0, 204, 0))); // NOI18N

        opcCine.setText("Cine");

        opcLeer.setText("Leer");

        opcProgramar.setText("Programar");

        opcDeportes.setText("Deportes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcLeer)
                    .addComponent(opcCine))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(opcProgramar)
                    .addComponent(opcDeportes))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcProgramar)
                    .addComponent(opcCine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcLeer)
                    .addComponent(opcDeportes))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        comboSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione ..", "USUARIO", "ADMINISTRADOR" }));
        comboSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionActionPerformed(evt);
            }
        });

        jLabel6.setText("Rol:");

        jLabel9.setText("Password:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CampoEmail)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(CampoCedula)
                                            .addComponent(CampoPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                            .addComponent(CampoNombre)
                                            .addComponent(CampoPassword2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(CampoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addComponent(comboSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CampoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(CampoPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CampoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        botonCancelarCrud.setText("Cancelar");
        botonCancelarCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarCrudActionPerformed(evt);
            }
        });

        botonAgregarCrud.setText("AGREGAR");
        botonAgregarCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarCrudActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 153, 51));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setText("FORMULARIO DATOS DEL USUARIO");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(botonCancelarCrud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonBuscar)
                .addGap(18, 18, 18)
                .addComponent(botonAgregarCrud)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelarCrud)
                    .addComponent(botonAgregarCrud)
                    .addComponent(botonBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSeleccionActionPerformed

    private void botonAgregarCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarCrudActionPerformed

        String cc = null;
        try {
            cc = CampoCedula.getText();
            Integer cedula = Integer.parseInt(cc);
        } catch (NumberFormatException error) {
            JOptionPane.showMessageDialog(this, "La cedula debe ser numero",
                    "Error de Formato",
                    JOptionPane.ERROR_MESSAGE);
            return;

        }
        char[] pass1 = CampoPassword1.getPassword();
        String clave1 = String.valueOf(pass1);

        char[] pass2 = CampoPassword2.getPassword();
        String clave2 = String.valueOf(pass2);

        if (!clave1.equals(clave2)) {
            JOptionPane.showMessageDialog(this, "Los Password son diferente",
                    "Claves no son iguales",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (clave1.isEmpty() || clave2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los Password son necesarios",
                    "Claves vacias",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nombre = CampoNombre.getText();
        if (nombre == null || nombre.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre es necesario",
                    "Nombre vacio",
                    JOptionPane.ERROR_MESSAGE);

            CampoNombre.setText("");
            return;
        }

        char partesDelNombre[] = nombre.toCharArray();
        for (int i = 0; i < nombre.length(); i++) {
            char caracter = nombre.charAt(i);
            if (Character.isDigit(caracter)) {
                JOptionPane.showMessageDialog(this, "Nombre con formato invalido",
                        "Nombre incorrecto",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        /*for (char caracter : partesDelNombre) {
            if(Character.isDigit(caracter))
            {
                JOptionPane.showMessageDialog(this, "Nombre con formato invalido",
                        "Nombre incorrecto",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }*/
        String email = CampoEmail.getText();
        if (email != null && !email.isEmpty()) {
            int cuenta = 0;
            for (int i = 0; i < email.length(); i++) {
                char arroba = email.charAt(i);
                if (arroba == '@') {
                    cuenta++;
                }
                if (cuenta > 1) {
                    JOptionPane.showMessageDialog(this, "Email con formato invalido",
                            "Email incorrecto",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            if (cuenta == 0 || email.startsWith("@") || email.endsWith("@")) {
                JOptionPane.showMessageDialog(this, "Email con formato invalido",
                        "Email incorrecto",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        Date fechaNacimiento = CampoFecha.getDate();
        Date fechaActual = new Date();
        try {
            if (fechaNacimiento.after(fechaActual)) {
                JOptionPane.showMessageDialog(this, "Fecha de nacimiento mayor que la fecha actual",
                        "Fecha incorrecta",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NullPointerException error) {
            JOptionPane.showMessageDialog(this, "Seleccione una fecha",
                    "Fecha incorrecta",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String genero = null;
        if (radioMasculino.isSelected()) {
            genero = "Masculino";
        } else if (radioFemenino.isSelected()) {
            genero = "Femenino";
        } else if (radioOtros.isSelected()) {
            genero = "Otros";
        }
        
        String pasatiempos = "";
        if (opcCine.isSelected()) {
            pasatiempos += opcCine.getText() + ",";
        }
        if (opcLeer.isSelected()) {
            pasatiempos += opcLeer.getText() + ",";
        }
        if (opcProgramar.isSelected()) {
            pasatiempos += opcProgramar.getText() + ",";
        }
        if (opcDeportes.isSelected()) {
            pasatiempos += opcDeportes.getText() + ",";
        }
        
        String rol = null;
        if (comboSeleccion.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un Rol",
                    "Error Formulario",
                    JOptionPane.ERROR_MESSAGE);
            return;

        } else {
            rol = (String) comboSeleccion.getSelectedItem();
        }

        EntityManagerFactory conexion = Persistence.createEntityManagerFactory("conexion");
        UsuarioJpaController crudUsuario = new UsuarioJpaController(conexion);

        Usuario u = new Usuario(cc, nombre);

        u.setEmail(email);
        u.setFechaNacimiento(fechaNacimiento);
        u.setGenero(genero);
        u.setHobbies(pasatiempos);
        u.setClave(clave1);
        u.setRol(rol);

        try {
            int opcion = JOptionPane.showConfirmDialog(this, "Esta seguro de Registrar",
                    "CONFIRMAR", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opcion == JOptionPane.YES_NO_OPTION) {
                crudUsuario.create(u);
                int totalUsuario = crudUsuario.getUsuarioCount();
                JOptionPane.showMessageDialog(this, "Usuario Registrado \nTotal:" + totalUsuario);
                limpiarFormulario();
            }

        } catch (PreexistingEntityException error1) {
            JOptionPane.showMessageDialog(this, "El Usuario Ya Existe",
                    "Error de BD",
                    JOptionPane.ERROR_MESSAGE);

        } catch (Exception error1) {
            JOptionPane.showMessageDialog(this, "Problema con la BD",
                    "Error de BD",
                    JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_botonAgregarCrudActionPerformed

    private void CampoCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoCedulaKeyTyped
        char tecla = evt.getKeyChar();
        if (!Character.isDigit(tecla)) {
            evt.consume();
            Toolkit.getDefaultToolkit();
        }

    }//GEN-LAST:event_CampoCedulaKeyTyped

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed

        String cedula = CampoCedula.getText();
        if (cedula == null || cedula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La Cedula es necesaria",
                    "Cedula vacias",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            EntityManagerFactory conexion = Persistence.createEntityManagerFactory("conexion");
            UsuarioJpaController crudUsuario = new UsuarioJpaController(conexion);

            Usuario u = crudUsuario.findUsuario(cedula);
            if (u == null) {
                JOptionPane.showMessageDialog(this, "El Usuario con CC " + cedula + "No existe",
                        "Cedula Vacias",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            limpiarFormulario();
            CampoCedula.setText(u.getCedula());
            CampoPassword1.setText(u.getClave());
            CampoPassword2.setText(u.getClave());
            CampoNombre.setText(u.getNombre());
            CampoEmail.setText(u.getEmail());
            CampoFecha.setDate(u.getFechaNacimiento());
            if (u.getGenero().equalsIgnoreCase("Masculino")) {
                radioMasculino.setSelected(true);
            } else if (u.getGenero().equalsIgnoreCase("Femenino")) {
                radioFemenino.setSelected(true);
            }
            if (u.getGenero().equalsIgnoreCase("Otros")) {
                radioOtros.setSelected(true);
            }

            String hobbies = u.getHobbies();
            if (hobbies.indexOf(opcCine.getText()) >= 0) {
                opcCine.setSelected(true);
            }
            if (hobbies.indexOf(opcLeer.getText()) >= 0) {
                opcLeer.setSelected(true);
            }
            if (hobbies.indexOf(opcProgramar.getText()) >= 0) {
                opcProgramar.setSelected(true);
            }
            if (hobbies.indexOf(opcDeportes.getText()) >= 0) {
                opcDeportes.setSelected(true);
            }
            comboSeleccion.setSelectedItem(u.getRol());

        } catch (PersistenceException error) {
            JOptionPane.showMessageDialog(this, "Error de conexin con BD",
                    "Server BD apagada",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }


    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonCancelarCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarCrudActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarCrudActionPerformed
    public void limpiarFormulario() {
        CampoCedula.setText("");
        CampoPassword1.setText("");
        CampoPassword2.setText("");
        CampoNombre.setText("");
        CampoEmail.setText("");
        CampoFecha.cleanup();
        comboSeleccion.setSelectedIndex(0);
        opcCine.setSelected(false);
        opcLeer.setSelected(false);
        opcProgramar.setSelected(false);
        opcDeportes.setSelected(false);
        radioFemenino.setSelected(false);
        radioMasculino.setSelected(false);
        radioOtros.setSelected(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCrud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaCrud dialog = new VentanaCrud(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoCedula;
    private javax.swing.JTextField CampoEmail;
    private com.toedter.calendar.JDateChooser CampoFecha;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JPasswordField CampoPassword1;
    private javax.swing.JPasswordField CampoPassword2;
    private javax.swing.JButton botonAgregarCrud;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonCancelarCrud;
    private javax.swing.JComboBox<String> comboSeleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox opcCine;
    private javax.swing.JCheckBox opcDeportes;
    private javax.swing.JCheckBox opcLeer;
    private javax.swing.JCheckBox opcProgramar;
    private javax.swing.JRadioButton radioFemenino;
    private javax.swing.JRadioButton radioMasculino;
    private javax.swing.JRadioButton radioOtros;
    // End of variables declaration//GEN-END:variables
}
